"""catalog_load.etl_run_id (D36)

Revision ID: 9662e27ae314
Revises: 690574b6e935
Create Date: 2026-09-30 11:39:49.940653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9662e27ae314'
down_revision: Union[str, Sequence[str], None] = '690574b6e935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_load', sa.Column('etl_run_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_catalog_load_etl_run_id'), 'catalog_load', 'etl_run', ['etl_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_catalog_load_etl_run_id'), 'catalog_load', type_='foreignkey')
    op.drop_column('catalog_load', 'etl_run_id')
    # ### end Alembic commands ###
