"""tablas del MVP: etl_run, etl_run_event, price_load, mail_recipient, mail_log

Revision ID: a7e8da06c311
Revises: 
Create Date: 2026-09-24 16:39:03.173132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7e8da06c311'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_run',
    sa.Column('status', sa.Enum('queued', 'running', 'ok', 'partial', 'failed', name='run_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('trigger', sa.Enum('cron', 'manual', name='run_trigger', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('market_codes', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unmatched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('gaps_esc1', sa.Integer(), nullable=True),
    sa.Column('gaps_esc2', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_run'))
    )
    op.create_index('ix_etl_run_created_at', 'etl_run', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_etl_run_active', 'etl_run', [sa.literal_column('(true)')], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_table('mail_recipient',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('notify_start', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_end', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_recipient')),
    sa.UniqueConstraint('email', name=op.f('uq_mail_recipient_email'))
    )
    op.create_table('etl_run_event',
    sa.Column('etl_run_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='event_level', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('market_code', sa.String(length=20), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], name=op.f('fk_etl_run_event_etl_run_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_run_event'))
    )
    op.create_index('ix_etl_run_event_etl_run_id_id', 'etl_run_event', ['etl_run_id', 'id'], unique=False)
    op.create_table('mail_log',
    sa.Column('etl_run_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('start', 'end', name='mail_kind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('recipients', postgresql.ARRAY(sa.String(length=254)), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', 'skipped', name='mail_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], name=op.f('fk_mail_log_etl_run_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_log'))
    )
    op.create_table('price_load',
    sa.Column('etl_run_id', sa.BigInteger(), nullable=False),
    sa.Column('market_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ok', 'partial', 'failed', 'skipped', name='load_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unmatched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unmatched_codes', postgresql.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], name=op.f('fk_price_load_etl_run_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_load')),
    sa.UniqueConstraint('etl_run_id', 'market_code', name=op.f('uq_price_load_etl_run_id_market_code'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_load')
    op.drop_table('mail_log')
    op.drop_index('ix_etl_run_event_etl_run_id_id', table_name='etl_run_event')
    op.drop_table('etl_run_event')
    op.drop_table('mail_recipient')
    op.drop_index('uq_etl_run_active', table_name='etl_run', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_etl_run_created_at', table_name='etl_run')
    op.drop_table('etl_run')
    # ### end Alembic commands ###
