"""catalog_load_item.kind (D34)

Revision ID: 690574b6e935
Revises: 2d22c4e04859
Create Date: 2026-09-25 13:43:09.231126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690574b6e935'
down_revision: Union[str, Sequence[str], None] = '2d22c4e04859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_load_item', sa.Column('kind', sa.String(length=10), server_default='product', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_load_item', 'kind')
    # ### end Alembic commands ###
