"""gap_report; rejected en price_load y etl_run; dry_run en etl_run

Revision ID: 26f3621d5a6e
Revises: a7e8da06c311
Create Date: 2026-09-24 17:30:38.034457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26f3621d5a6e'
down_revision: Union[str, Sequence[str], None] = 'a7e8da06c311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_report',
    sa.Column('etl_run_id', sa.BigInteger(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('markets', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('total_esc1', sa.Integer(), nullable=False),
    sa.Column('total_esc2', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Integer(), server_default='0', nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excel_filename', sa.String(length=80), nullable=False),
    sa.Column('excel', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], name=op.f('fk_gap_report_etl_run_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gap_report'))
    )
    op.create_index('ix_gap_report_created_at', 'gap_report', [sa.literal_column('created_at DESC')], unique=False)
    op.add_column('etl_run', sa.Column('dry_run', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('etl_run', sa.Column('rejected', sa.Integer(), server_default='0', nullable=False))
    op.add_column('price_load', sa.Column('rejected', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_load', 'rejected')
    op.drop_column('etl_run', 'rejected')
    op.drop_column('etl_run', 'dry_run')
    op.drop_index('ix_gap_report_created_at', table_name='gap_report')
    op.drop_table('gap_report')
    # ### end Alembic commands ###
