"""catalog_load y catalog_load_item (D33)

Revision ID: 2d22c4e04859
Revises: 26f3621d5a6e
Create Date: 2026-09-25 13:07:28.699586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d22c4e04859'
down_revision: Union[str, Sequence[str], None] = '26f3621d5a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_load',
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('validated', 'invalid', 'applied', 'partial', 'failed', name='catalog_load_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('invalid', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_load'))
    )
    op.create_index('ix_catalog_load_created_at', 'catalog_load', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('catalog_load_item',
    sa.Column('catalog_load_id', sa.BigInteger(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('crop_code', sa.String(length=10), nullable=False),
    sa.Column('outcome', sa.Enum('planned', 'created', 'skipped_exists', 'invalid', 'error', name='registration_outcome', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_load_id'], ['catalog_load.id'], name=op.f('fk_catalog_load_item_catalog_load_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_load_item'))
    )
    op.create_index('ix_catalog_load_item_catalog_load_id_row_number', 'catalog_load_item', ['catalog_load_id', 'row_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_load_item_catalog_load_id_row_number', table_name='catalog_load_item')
    op.drop_table('catalog_load_item')
    op.drop_index('ix_catalog_load_created_at', table_name='catalog_load')
    op.drop_table('catalog_load')
    # ### end Alembic commands ###
