"""mail_recipient.notify_error y mail_kind error (D37)

Revision ID: 59cee1116a87
Revises: 9662e27ae314
Create Date: 2026-09-30 12:25:46.467800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cee1116a87'
down_revision: Union[str, Sequence[str], None] = '9662e27ae314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_recipient', sa.Column('notify_error', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###
    # mail_log.kind es un enum no nativo con CHECK: autogenerate no ve el valor nuevo 'error'.
    op.drop_constraint(op.f('ck_mail_log_mail_kind'), 'mail_log', type_='check')
    op.create_check_constraint(op.f('ck_mail_log_mail_kind'), 'mail_log', "kind IN ('start', 'end', 'error')")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM mail_log WHERE kind = 'error'")
    op.drop_constraint(op.f('ck_mail_log_mail_kind'), 'mail_log', type_='check')
    op.create_check_constraint(op.f('ck_mail_log_mail_kind'), 'mail_log', "kind IN ('start', 'end')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail_recipient', 'notify_error')
    # ### end Alembic commands ###
